import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native'
import { SafeAreaView } from 'react-native-safe-area-context'
import { useLocalSearchParams, useRouter } from 'expo-router'
import { Ionicons } from '@expo/vector-icons'
import { useApp } from '@/context/AppContext'
import { Button, Header } from '@/components/UI'
import { C, shadow } from '@/theme'

export default function OrderDetail() {
  const router = useRouter(); const { id } = useLocalSearchParams<{ id: string }>(); const { history, reorder, rateOrder } = useApp(); const record = history.find((item) => item.id === id)
  if (!record) return <SafeAreaView style={styles.safe}><Header title="PEDIDO" onBack={() => router.back()}/><View style={styles.missing}><Text style={styles.missingTitle}>NO ENCONTRADO.</Text></View></SafeAreaView>
  const repeat = () => { const ok = reorder(record.id); if (ok) router.replace('/checkout'); else Alert.alert('No disponible','Los envíos y ciertos pedidos históricos no pueden repetirse automáticamente.') }
  return <SafeAreaView style={styles.safe} edges={['top','bottom']}><Header title={record.id} kicker="DETALLE DE OPERACIÓN" onBack={() => router.back()}/><ScrollView contentContainerStyle={styles.content}>
    <View style={[styles.hero, record.kind === 'shipment' && { backgroundColor: C.mint }]}><Text style={styles.kind}>{record.kind === 'shipment' ? 'ENVÍO COMPLETADO' : 'PEDIDO COMPLETADO'}</Text><Text style={styles.title}>{record.title.toUpperCase()}</Text><Text style={styles.summary}>{record.summary}</Text><View style={styles.total}><Text style={styles.totalLabel}>TOTAL</Text><Text style={styles.totalValue}>S/ {record.total.toFixed(2)}</Text></View></View>
    <View style={styles.timeline}>{['Confirmado','Preparado','En camino','Entregado'].map((step,index)=><View key={step} style={styles.step}><View style={styles.stepIcon}><Text style={styles.stepNumber}>{index+1}</Text></View><View style={{flex:1}}><Text style={styles.stepTitle}>{step.toUpperCase()}</Text><Text style={styles.stepCopy}>{index===3?record.date:'Completado durante la operación'}</Text></View><Ionicons name="checkmark-circle" size={22} color="#087457"/></View>)}</View>
    <Text style={styles.section}>RESUMEN</Text><View style={styles.receipt}><View style={styles.receiptRow}><Text style={styles.receiptLabel}>Operación</Text><Text style={styles.receiptValue}>{record.id}</Text></View><View style={styles.receiptRow}><Text style={styles.receiptLabel}>Estado</Text><Text style={styles.receiptValue}>{record.status}</Text></View><View style={styles.receiptRow}><Text style={styles.receiptLabel}>Fecha</Text><Text style={styles.receiptValue}>{record.date}</Text></View><View style={styles.receiptRow}><Text style={styles.receiptLabel}>Método</Text><Text style={styles.receiptValue}>Visa •••• 4242</Text></View></View>
    {!record.rated ? <Button label="CALIFICAR EXPERIENCIA" onPress={()=>{rateOrder(record.id);Alert.alert('Gracias','Tu calificación demo fue registrada.')}} color="yellow" icon="star-outline"/> : <View style={styles.rated}><Ionicons name="star" size={20}/><Text style={styles.ratedText}>EXPERIENCIA CALIFICADA</Text></View>}
    <View style={{height:10}}/><Button label={record.kind==='order'?'REPETIR PEDIDO':'NUEVO ENVÍO'} onPress={record.kind==='order'?repeat:()=>router.push('/store/10')} color="black" icon="refresh"/>
    <Pressable onPress={()=>router.push('/support')} style={styles.help}><Text style={styles.helpText}>¿PROBLEMAS CON ESTA OPERACIÓN?</Text><Text style={styles.helpArrow}>ABRIR SOPORTE →</Text></Pressable>
  </ScrollView></SafeAreaView>
}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:C.paper},content:{padding:16,paddingBottom:35},missing:{flex:1,alignItems:'center',justifyContent:'center'},missingTitle:{fontSize:34,fontWeight:'900'},hero:{minHeight:230,padding:17,borderWidth:2,borderColor:C.black,backgroundColor:C.blue,...shadow},kind:{color:C.white,fontSize:8,fontWeight:'900',letterSpacing:1},title:{marginTop:17,color:C.yellow,fontSize:34,lineHeight:30,fontWeight:'900',letterSpacing:-1.7},summary:{marginTop:9,color:C.white,fontSize:9},total:{marginTop:'auto',paddingTop:12,flexDirection:'row',justifyContent:'space-between',alignItems:'flex-end',borderTopWidth:1,borderColor:C.white},totalLabel:{color:C.white,fontSize:8,fontWeight:'900'},totalValue:{color:C.white,fontSize:26,fontWeight:'900'},timeline:{marginTop:19},step:{minHeight:69,padding:10,flexDirection:'row',alignItems:'center',gap:10,borderWidth:2,borderBottomWidth:0,borderColor:C.black,backgroundColor:C.white},stepIcon:{width:38,height:38,alignItems:'center',justifyContent:'center',borderWidth:2,borderColor:C.black,borderRadius:19,backgroundColor:C.mint},stepNumber:{fontSize:15,fontWeight:'900'},stepTitle:{fontSize:9,fontWeight:'900'},stepCopy:{marginTop:4,color:C.gray,fontSize:8},section:{marginTop:26,marginBottom:10,fontSize:18,fontWeight:'900'},receipt:{marginBottom:18,padding:13,borderWidth:2,borderColor:C.black,backgroundColor:C.white},receiptRow:{minHeight:35,flexDirection:'row',justifyContent:'space-between',alignItems:'center',borderBottomWidth:1,borderColor:C.line},receiptLabel:{fontSize:8,color:C.gray},receiptValue:{fontSize:8,fontWeight:'900'},rated:{minHeight:52,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:8,borderWidth:2,borderColor:C.black,backgroundColor:C.mint},ratedText:{fontSize:9,fontWeight:'900'},help:{minHeight:70,marginTop:18,padding:12,borderWidth:2,borderColor:C.black,backgroundColor:C.white},helpText:{fontSize:8,fontWeight:'900'},helpArrow:{marginTop:8,color:C.blue,fontSize:9,fontWeight:'900'}})
