import fs from 'node:fs'
import path from 'node:path'
const root=process.cwd(); const read=(f)=>fs.readFileSync(path.join(root,f),'utf8'); const checks=[]; const check=(n,c)=>checks.push({n,ok:Boolean(c)})
const pkg=JSON.parse(read('package.json')); const app=JSON.parse(read('app.json')).expo; const business=read('app/business.tsx'); const profile=read('app/business-profile.tsx'); const context=read('context/AppContext.tsx'); const persistence=read('services/persistence.ts')
check('versión Business 2.3.0',pkg.version==='2.3.0'&&app.version==='2.3.0')
check('Android versionCode 23',app.android.versionCode===23)
check('iOS buildNumber 23',app.ios.buildNumber==='23')
check('perfil comercial dedicado',fs.existsSync(path.join(root,'app/business-profile.tsx'))&&business.includes("router.push('/business-profile')"))
check('perfil por comercio',context.includes('businessProfiles')&&context.includes('currentBusinessProfile'))
check('schema persistente v8',context.includes('schemaVersion: 8')&&persistence.includes('APP_SCHEMA_VERSION = 8'))
check('migración desde schema 7',persistence.includes('[1, 2, 3, 4, 5, 6, 7, APP_SCHEMA_VERSION]'))
check('nombre canónico bloqueado',profile.includes('El nombre canónico permanece bloqueado'))
check('contacto comercial validado',profile.includes('emailPattern')&&profile.includes('7 y 15 números'))
check('cambios sin guardar protegidos',profile.includes('Cambios sin guardar')&&profile.includes('hardwareBackPress'))
check('métricas operativas dinámicas',business.includes('operationalScore')&&business.includes('acceptanceRate')&&business.includes('averageEta'))
check('sin valores operativos fijos antiguos',!business.includes('91/100')&&!business.includes('98%')&&!business.includes('14 min'))
check('estado de Sync Hub visible',business.includes('SYNC HUB')&&business.includes('pendingActions'))
check('polling solo en primer plano',context.includes("lastLifecycleState !== 'active'")&&context.includes('5500 : 3000'))
check('inventario explícito y reversible',context.includes('setMerchantProductAvailability')&&!context.includes('state.stock[productId] === false'))
check('editor profesional por producto',fs.existsSync(path.join(root,'app/product/[id].tsx'))&&business.includes('ProductPhoto'))
check('Business aislada de otras interfaces',!fs.existsSync(path.join(root,'app/(tabs)'))&&!fs.existsSync(path.join(root,'app/rider.tsx'))&&!fs.existsSync(path.join(root,'app/admin.tsx')))
const failed=checks.filter(x=>!x.ok); for(const x of checks) console.log(`${x.ok?'PASS':'FAIL'} · ${x.n}`); console.log(`\n${checks.length-failed.length}/${checks.length} verificaciones Business aprobadas.`); if(failed.length)process.exit(1)
