import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native'
import { SafeAreaView } from 'react-native-safe-area-context'
import { useRouter } from 'expo-router'
import { categoryByKey, promos } from '@/data/catalog'
import { useApp } from '@/context/AppContext'
import { C, shadow, tone } from '@/theme'

export default function Wallet(){
  const router=useRouter(); const {walletBalance,selectedPayment,walletEntries}=useApp()
  return <SafeAreaView style={styles.safe} edges={['top']}><ScrollView contentContainerStyle={styles.content}>
    <Text style={styles.kicker}>BILLETERA Y BENEFICIOS</Text><Text style={styles.title}>DINERO.{`\n`}SIN MEZCLAS.</Text>
    <View style={styles.wallet}><Text style={styles.label}>SALDO DELIVER ASSETS</Text><Text style={styles.balance}>S/ {walletBalance.toFixed(2)}</Text><Text style={styles.copy}>Saldo completamente simulado</Text><View style={styles.logo}><Text style={styles.logoText}>DA</Text></View><Pressable onPress={()=>Alert.alert('Saldo demo','No es posible agregar dinero real en este prototipo.')} style={styles.add}><Text style={styles.addText}>AGREGAR SALDO</Text></Pressable></View>
    <Pressable onPress={()=>router.push('/payments')} style={styles.payment}><View><Text style={styles.paymentLabel}>MÉTODO PREDETERMINADO</Text><Text style={styles.paymentTitle}>{selectedPayment.label.toUpperCase()}</Text><Text style={styles.paymentCopy}>{selectedPayment.detail}</Text></View><Text style={styles.paymentArrow}>→</Text></Pressable>
    <Text style={styles.section}>PROMOCIONES POR CATEGORÍA</Text><View style={styles.rule}><Text style={styles.ruleTitle}>REGLA PERMANENTE: SIN MEZCLAS</Text><Text style={styles.ruleCopy}>Cada beneficio indica exactamente dónde puede usarse. Un cupón de comida nunca se aplica a mercado, farmacia o envíos.</Text></View>
    {promos.map((promo)=><Pressable key={promo.code} onPress={()=>Alert.alert(promo.code,`${promo.detail}. Promoción simulada.`)} style={[styles.promo,{backgroundColor:tone(promo.tone)}]}><Text style={styles.promoCategory}>{promo.category==='all'?'GENERAL':categoryByKey(promo.category).label.toUpperCase()}</Text><Text style={styles.promoCode}>{promo.code}</Text><Text style={styles.promoTitle}>{promo.title.toUpperCase()}</Text><Text style={styles.promoCopy}>{promo.detail}</Text><Text style={styles.promoAction}>VER CONDICIONES →</Text></Pressable>)}
    <View style={styles.activity}><Text style={styles.activityTitle}>ACTIVIDAD FINANCIERA REAL DEL PROTOTIPO</Text>{walletEntries.slice(0,8).map(entry=>{const date=new Date(entry.createdAt).toLocaleDateString('es-PE',{day:'2-digit',month:'short'}).toUpperCase();const sign=entry.direction==='credit'?'+':'−';return <View key={entry.id} style={styles.activityRow}><Text style={styles.activityDate}>{date}</Text><Text style={styles.activityName}>{entry.label}</Text><Text style={[styles.activityValue,entry.direction==='credit'&&{color:'#087457'}]}>{sign} S/ {entry.amount.toFixed(2)}</Text></View>})}{walletEntries.length===0&&<View style={styles.activityRow}><Text style={styles.activityName}>Sin movimientos todavía.</Text></View>}</View>
  </ScrollView></SafeAreaView>
}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:C.paper},content:{padding:16,paddingBottom:110},kicker:{fontSize:9,fontWeight:'900',letterSpacing:1.2},title:{marginTop:10,fontSize:47,lineHeight:39,fontWeight:'900',letterSpacing:-2.4},wallet:{marginTop:23,minHeight:245,padding:18,borderWidth:2,borderColor:C.black,backgroundColor:C.black,...shadow},label:{color:C.white,fontSize:8,fontWeight:'900'},balance:{marginTop:18,color:C.mint,fontSize:53,fontWeight:'900',letterSpacing:-2.5},copy:{color:'#B8B3AA',fontSize:9},logo:{position:'absolute',right:18,top:18,width:56,height:56,borderWidth:2,borderColor:C.white,backgroundColor:C.red,alignItems:'center',justifyContent:'center',transform:[{rotate:'-7deg'}]},logoText:{color:C.white,fontSize:21,fontWeight:'900'},add:{position:'absolute',left:18,right:18,bottom:18,minHeight:42,borderWidth:2,borderColor:C.white,backgroundColor:C.yellow,alignItems:'center',justifyContent:'center'},addText:{fontSize:9,fontWeight:'900'},payment:{minHeight:95,marginTop:18,padding:14,flexDirection:'row',alignItems:'center',justifyContent:'space-between',borderWidth:2,borderColor:C.black,backgroundColor:C.white},paymentLabel:{fontSize:7,fontWeight:'900'},paymentTitle:{marginTop:7,fontSize:18,fontWeight:'900'},paymentCopy:{marginTop:4,color:C.gray,fontSize:8},paymentArrow:{fontSize:26,fontWeight:'900'},section:{marginTop:31,marginBottom:11,fontSize:20,fontWeight:'900'},rule:{marginBottom:11,padding:13,borderWidth:2,borderColor:C.black,backgroundColor:C.white},ruleTitle:{fontSize:9,fontWeight:'900'},ruleCopy:{marginTop:4,color:C.gray,fontSize:8,lineHeight:12},promo:{minHeight:180,padding:16,borderWidth:2,borderColor:C.black,marginBottom:11},promoCategory:{alignSelf:'flex-start',paddingHorizontal:7,paddingVertical:4,borderWidth:1,borderColor:C.black,backgroundColor:C.white,fontSize:7,fontWeight:'900'},promoCode:{marginTop:16,fontSize:26,fontWeight:'900'},promoTitle:{marginTop:9,fontSize:22,lineHeight:21,fontWeight:'900'},promoCopy:{marginTop:7,fontSize:9},promoAction:{marginTop:16,fontSize:9,fontWeight:'900'},activity:{marginTop:20,borderWidth:2,borderColor:C.black,backgroundColor:C.white},activityTitle:{padding:13,borderBottomWidth:2,borderColor:C.black,backgroundColor:C.black,color:C.white,fontSize:9,fontWeight:'900'},activityRow:{minHeight:58,padding:10,flexDirection:'row',alignItems:'center',gap:8,borderBottomWidth:1,borderColor:C.line},activityDate:{width:42,fontSize:7,fontWeight:'900'},activityName:{flex:1,fontSize:9,fontWeight:'800'},activityValue:{fontSize:9,fontWeight:'900'}})
