import fs from 'node:fs'
import path from 'node:path'

const root = process.cwd()
const read = (file) => fs.readFileSync(path.join(root, file), 'utf8')
const exists = (file) => fs.existsSync(path.join(root, file))
const checks = []
const check = (name, condition) => checks.push({ name, ok: Boolean(condition) })

const pkg = JSON.parse(read('package.json'))
const app = JSON.parse(read('app.json')).expo
const context = read('context/AppContext.tsx')
const persistence = read('services/persistence.ts')
const cartPersistence = read('services/cartPersistence.ts')
const backend = read('services/backend.ts')
const profile = read('app/profile.tsx')
const product = read('app/product/[id].tsx')
const cartScreen = read('app/cart.tsx')
const cartDock = read('components/CartDock.tsx')
const account = read('app/(tabs)/account.tsx')
const home = read('app/(tabs)/index.tsx')
const orders = read('app/(tabs)/orders.tsx')
const checkout = read('app/checkout.tsx')

check('versión 2.8.0 sincronizada', pkg.version === '2.8.0' && app.version === '2.8.0')
check('Android versionCode 28', app.android.versionCode === 28)
check('iOS buildNumber 28', app.ios.buildNumber === '28')
check('expo-image-picker recomendado', pkg.dependencies['expo-image-picker'] === '~17.0.11')
check('expo-file-system recomendado', pkg.dependencies['expo-file-system'] === '~19.0.23')
check('plugin de foto configurado', JSON.stringify(app.plugins).includes('expo-image-picker'))
check('perfil conserva photoUri', context.includes('photoUri?: string | null') && persistence.includes('photoUri'))
check('galería y cámara disponibles', profile.includes('launchImageLibraryAsync') && profile.includes('launchCameraAsync'))
check('resultado pendiente de Android recuperable', profile.includes('getPendingResultAsync'))
check('foto copiada a almacenamiento privado', exists('services/profilePhoto.ts') && read('services/profilePhoto.ts').includes('Paths.document'))
check('foto visible en cuenta', account.includes('ProfileAvatar') && account.includes('profile.photoUri'))
check('foto visible en inicio', home.includes('ProfileAvatar') && home.includes('profile.photoUri'))
check('pantalla de múltiples carritos', cartScreen.includes('TUS CARRITOS') && cartScreen.includes('MIS CARRITOS'))
check('dock muestra cantidad global y contexto de tienda', cartDock.includes('allCartCount') && cartDock.includes('cartStoreCount') && cartDock.includes('storeId?: number') && read('app/store/[id].tsx').includes('<CartDock storeId={store.id}/>'))
check('carrito con firmas estables', exists('data/cart.ts') && read('data/cart.ts').includes('cartLineSignature') && read('data/cart.ts').includes('addOrMergeCartLine'))
check('Context conserva líneas de varios comercios', context.includes('cartLines.filter((line) => line.storeId === resolvedActiveCartStoreId)') && context.includes('savedCarts'))
check('agregar en otro comercio no reemplaza', !product.includes('Cambiar de comercio') && context.includes('Tus otros carritos siguen guardados'))
check('cada comercio tiene checkout separado', cartScreen.includes('CHECKOUT SEPARADO') && cartScreen.includes('cada pedido se confirma y entrega por separado'))
check('vaciar carrito solo afecta comercio activo', context.includes('current.filter((line) => line.storeId !== resolvedActiveCartStoreId)'))
check('vaciar todos requiere función explícita', context.includes('clearAllCarts') && cartScreen.includes('VACIAR TODOS'))
check('copia primaria, respaldo y cola serial', cartPersistence.includes('CART_BACKUP_KEY') && cartPersistence.includes('recoveredFromBackup') && cartPersistence.includes('writeChain'))
check('cart schema v4 migra v3 y v2', cartPersistence.includes('CART_SCHEMA_VERSION = 4') && cartPersistence.includes('@deliver-assets/customer-cart-v3') && cartPersistence.includes('@deliver-assets/customer-cart-v2'))
check('carrito persistente conserva comercio activo', cartPersistence.includes('activeStoreId') && context.includes('setActiveCartStoreId'))
check('schema persistente v11', persistence.includes('APP_SCHEMA_VERSION = 11') && context.includes('schemaVersion: 11'))
check('migración desde schema v10', persistence.includes('[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, APP_SCHEMA_VERSION]'))
check('cerrar sesión no vacía carritos', !context.includes("const logout = () => { setAuthenticated(false); setGuestSession(false); setRole('cliente'); clearCart()"))
check('guardado inmediato al fondo incluye todos los carritos', context.includes('saveCartDraft(cartLines, promo, resolvedActiveCartStoreId, cartUpdatedAt)'))
check('sincronización al volver a primer plano', context.includes("lastLifecycleState !== 'active'") && context.includes('retryPendingActions'))
check('polling menos agresivo', context.includes("networkMode === 'slow' ? 5500 : 3000"))
check('cliente de Sync Hub actualizado', backend.includes('2.8.0-customer'))
check('script de arranque individual', exists('scripts/start-customer.ps1') && read('scripts/start-customer.ps1').includes('tcp:8081') && read('scripts/start-customer.ps1').includes('tcp:9090'))
check('estado de sincronización visible en pedidos', orders.includes('SYNC HUB CONECTADO') && orders.includes('lastHubSyncAt') && orders.includes('syncNow'))
check('pedidos muestra todos los carritos', orders.includes('allCartCount') && orders.includes('cartStoreCount'))
check('checkout usa ID estable de línea', checkout.includes('key={line.id}'))

const failed = checks.filter((item) => !item.ok)
for (const item of checks) console.log(`${item.ok ? 'PASS' : 'FAIL'} · ${item.name}`)
console.log(`\n${checks.length - failed.length}/${checks.length} verificaciones Customer aprobadas.`)
if (failed.length) process.exit(1)
