import { useState } from 'react'
import { KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native'
import { SafeAreaView } from 'react-native-safe-area-context'
import { useRouter } from 'expo-router'
import { Ionicons } from '@expo/vector-icons'
import { useApp } from '@/context/AppContext'
import { Header } from '@/components/UI'
import { C } from '@/theme'

const topics=['Problema con pedido','Pago o reembolso','DA Express','Cuenta y seguridad']
export default function Support(){const router=useRouter();const{supportMessages,sendSupportMessage}=useApp();const[text,setText]=useState('');const send=()=>{sendSupportMessage(text);setText('')};return <SafeAreaView style={styles.safe} edges={['top','bottom']}><Header title="DA SUPPORT" kicker="CENTRO DE RESOLUCIÓN" onBack={()=>router.back()}/><KeyboardAvoidingView style={{flex:1}} behavior={Platform.OS==='ios'?'padding':undefined}><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled">
<View style={styles.status}><View style={styles.dot}/><View style={{flex:1}}><Text style={styles.statusTitle}>SOPORTE DISPONIBLE</Text><Text style={styles.statusCopy}>Respuesta automática de demostración · no es atención real.</Text></View></View>
<Text style={styles.section}>TEMAS RÁPIDOS</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.topics}>{topics.map(topic=><Pressable key={topic} onPress={()=>setText(topic)} style={styles.topic}><Text style={styles.topicText}>{topic.toUpperCase()}</Text></Pressable>)}</ScrollView>
<View style={styles.chat}>{supportMessages.map(message=><View key={message.id} style={[styles.message,message.from==='user'?styles.user:styles.agent]}><Text style={[styles.messageFrom,message.from==='user'&&{color:C.white}]}>{message.from==='user'?'TÚ':'DA SUPPORT'}</Text><Text style={[styles.messageText,message.from==='user'&&{color:C.white}]}>{message.text}</Text><Text style={[styles.messageTime,message.from==='user'&&{color:'#D7D2CA'}]}>{message.time}</Text></View>)}</View>
</ScrollView><View style={styles.composer}><TextInput value={text} onChangeText={setText} placeholder="Escribe tu mensaje..." multiline style={styles.input}/><Pressable onPress={send} style={styles.send}><Ionicons name="send" size={21} color={C.white}/></Pressable></View></KeyboardAvoidingView></SafeAreaView>}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:C.paper},content:{padding:16,paddingBottom:25},status:{minHeight:72,padding:12,flexDirection:'row',alignItems:'center',gap:10,borderWidth:2,borderColor:C.black,backgroundColor:C.mint},dot:{width:14,height:14,borderWidth:2,borderColor:C.black,borderRadius:7,backgroundColor:C.white},statusTitle:{fontSize:9,fontWeight:'900'},statusCopy:{marginTop:4,fontSize:8,lineHeight:11},section:{marginTop:22,marginBottom:9,fontSize:17,fontWeight:'900'},topics:{gap:8,paddingRight:8},topic:{minHeight:39,paddingHorizontal:10,alignItems:'center',justifyContent:'center',borderWidth:2,borderColor:C.black,backgroundColor:C.white},topicText:{fontSize:7,fontWeight:'900'},chat:{marginTop:22,gap:10},message:{maxWidth:'84%',padding:12,borderWidth:2,borderColor:C.black},agent:{alignSelf:'flex-start',backgroundColor:C.white},user:{alignSelf:'flex-end',backgroundColor:C.blue},messageFrom:{fontSize:6,fontWeight:'900',letterSpacing:.8},messageText:{marginTop:6,fontSize:10,lineHeight:15},messageTime:{marginTop:7,color:C.gray,fontSize:7},composer:{minHeight:76,padding:10,flexDirection:'row',alignItems:'flex-end',gap:8,borderTopWidth:2,borderColor:C.black,backgroundColor:C.white},input:{flex:1,minHeight:50,maxHeight:100,padding:10,borderWidth:2,borderColor:C.black,backgroundColor:C.paper,fontSize:10,textAlignVertical:'top'},send:{width:50,height:50,alignItems:'center',justifyContent:'center',borderWidth:2,borderColor:C.black,backgroundColor:C.black}})
